#ref_db: /vortexfs1/omics/huber/shu/db/pr2-db/pr2_version_4.11.1_mothur.fasta
#ref_tax: /vortexfs1/omics/huber/shu/db/pr2-db/pr2_version_4.11.1_mothur.tax
ref_db: /vortexfs1/omics/huber/shu/db/pr2-db/pr2_version_4.12.0_18S_mothur.fasta
ref_tax: /vortexfs1/omics/huber/shu/db/pr2-db/pr2_version_4.12.0_18S_mothur.tax

#version: pr2_4.11.1
version: pr2_4.12.0
scratch: /vortexfs1/scratch/sarahhu

primerF: CCAGCASCYGCGGTAATTCC
primerR: ACTTTCGTTCTTGATYRA
db_region: V4
